config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"\
  get "/new", to: "game#new"
  post "/score", to: "game#score"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
require "json"
require "open-uri"


class GameController < ApplicationController
  def new
    @letterarray= ('A'..'Z').to_a.sample(10)
  end

  def score
    # userinput
    @letters = params[:letters].split
    @word = (params[:userinput] || "").upcase
    @included = included?(@word, @letters)
    @english_word = english_word?(@word)
  end

  private

  def included?(word, letters)
    word.chars.all? { |letter| word.count(letter) <= letters.count(letter) }
  end

  def english_word?(word)
    response = URI.open("https://wagon-dictionary.herokuapp.com/#{word}")
    json = JSON.parse(response.read)
    json['found']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12 ">
        <h1>New game</h1>
        <ul class="d-flex list-unstyled text-white">
          <% @letterarray.each do |word| %>
            <li class="p-4 bg-info m-2 fs-2"><%= word %></li>
          <% end %>
        </ul>
    </div>
    <div class="col-md-12 mt-3">
      <form class="row gx-3 gy-2 align-items-center" action="<%= score_path %>" method="POST" data-turbo="false">
          <label class="form-label" for="inputword">What is the longest word you can find?</label>
        <div class="col-sm-10 d-flex">
          <%# Pass letter value %>
          <%= hidden_field_tag :letters, @letters %>
          <%# Pass Token here to check it came from this website or not %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <input type="text" class="form-control" id="inputword" name="inputword" placeholder="Add Word">
          <button type="submit" class="btn btn-primary">Play</button>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/game/score.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12 ">
        <h1>Result </h1>
        <% if @included %>
          <% if @english_word %>
            <p><strong>Congratulations!</strong> <%= @word %> is a valid English word!</p>
          <% else %>
            <p>Sorry but <strong><%= @word %></strong> does not seem to be a valid English word...</p>
          <% end %>
        <% else %>
          <p>Sorry but <strong><%= @word %></strong> can't be built out of <%= @letterarray.join(", ") %></p>
        <% end %>
        <%= link_to "try Again", new_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# Add bootstrap Css %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>